version: '3.7'
services:
  db:
    image: postgres
    container_name: mesh_task
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mesh_task
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

